### ISSUE TITLE
Is there a way to reverse switch buttons?

### ISSUE THREAD

**Issue by Rarst** [ghinda/css-toggle-switch#53]
From documentation is seems implicitly that first switch buttons always corresponds to checkbox `off` and second button to checkbox `on`.

I am working on existing UI where some legacy settings are "check to disable". That is checkbox `on` leads to corresponding setting item getting _disabled_.

Replacing it with switch already helps a lot since I can provide clear label for states. However it results in some switches having _enabled_ state on the right and some on the left. Also I can't style _disabled_ state separately, since again it can be on the left or right.

![yoast-toggle-order](https://cloud.githubusercontent.com/assets/737584/12064343/43d1f30a-afc9-11e5-8fd8-511acd33c56e.png)

Is there a possibility of reversing order of switch buttons for some of switches?

**Comment by Rarst** [comment]
Ok, I seem to have managed it. :)

```css
.switch-light.switch-yoast-seo-reverse input:checked ~ span a {
    left: 0;
}

.switch-light.switch-yoast-seo-reverse a {
    left: 50%;
}

.switch-light.switch-yoast-seo-reverse span span {
    float: right;
}
```
