### ISSUE TITLE
Request for already minified file in distro

### ISSUE THREAD

**Issue by mtgibbs** [ghinda/css-toggle-switch#59]
Hey guys,

I have an issue with minifying the content of the 4.0.2 build using Microsoft's MVC Bundler.  Could we provide an already minified file in the distro?

```
/* Minification failed. Returning unminified contents.
(7845,28): run-time error CSS1019: Unexpected token, found '}'
(7854,1): run-time error CSS1019: Unexpected token, found '@-webkit-keyframes'
(7855,8): run-time error CSS1035: Expected colon, found '{'
(9829,1): run-time error CSS1019: Unexpected token, found '@keyframes'
(9830,3): run-time error CSS1062: Expected semicolon or closing curly-brace, found '20%'
(9854,1): run-time error CSS1019: Unexpected token, found '@keyframes'
(9855,3): run-time error CSS1062: Expected semicolon or closing curly-brace, found '0%'
 */
```

**Comment by ghinda** [comment]
What file is it trying to minify?
Do you know what the MVC Bundler is using for minification? So I can test it on my end.

I would like to avoid including minified files, and rather fix the current `dist/` files to work with any minifier.

**Comment by mtgibbs** [comment]
Thanks for your response.

That makes sense.  The MVC bundler is its own implementation as far as I know.  I tested minifying this with other tools available and it works, so it could be a problem with their implementation.  Heck, it could be a problem with how they're concating the files.  If you prefer to make it work with other minifiers, I'll take some time and see if I can make a repro project to make it easy to track down.

**Comment by ghinda** [comment]
I released a new version `4.0.3`, built with a newer version of `node-sass`.
Can you check if you still get the error?

**Comment by mtgibbs** [comment]
Unfortunately the error is still occurring with 4.0.3.

```
/* Minification failed. Returning unminified contents.
(471,28): run-time error CSS1019: Unexpected token, found '}'
(481,1): run-time error CSS1019: Unexpected token, found '@-webkit-keyframes'
(482,8): run-time error CSS1035: Expected colon, found '{'
 */
```

So the error at least manifests in this block:

```css
 /* trick to prevent the default checked ripple animation from showing
 * when the page loads.
 * the ripples are hidden by default, and shown only when the input is focused.
 */
  .switch-light.switch-material.switch-light input ~ span:before,
  .switch-light.switch-material.switch-light input ~ span:after,
  .switch-material.switch-toggle input + label:after {
    visibility: hidden; }
  .switch-light.switch-material.switch-light input:focus:checked ~ span:before,
  .switch-light.switch-material.switch-light input:focus:not(:checked) ~ span:after,
  .switch-material.switch-toggle input:focus:checked + label:after {
    visibility: visible; } }

/* Bugfix for older Webkit, including mobile Webkit. Adapted from
 * http://css-tricks.com/webkit-sibling-bug/
 */
@media only screen and (-webkit-max-device-pixel-ratio: 2) and (max-device-width: 80em) {
  .switch-light,
  .switch-toggle {
    -webkit-animation: webkitSiblingBugfix infinite 1s; } }

@-webkit-keyframes webkitSiblingBugfix {
  from {
    -webkit-transform: translate3d(0, 0, 0); }
  to {
    -webkit-transform: translate3d(0, 0, 0); } }
```

Looking through this though, I don't see any of this as invalid, so their parser for MVC bundler is doing something weird, but I can't seem to get it to give me a better explanation or log right now.
